version: "3.7"
services:
  mysql_db:
    image: "mysql:8.0"
    container_name: mysqlserver
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: filmes
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db_mysql:/var/lib/db_mysql

volumes:
  db_mysql:
